### ISSUE TITLE
[FR]Auto close the preview after mouse moved away

### ISSUE THREAD

**Issue by ErickWei** [ejbills/DockDoor#398]
## Problem or Need
Sometimes,the preview dialog not close after mouse moved away.i dont know if it is a bug or something.

https://github.com/user-attachments/assets/02bf1d5e-7c0b-4e60-a69c-9fb5a7b26a80
## Proposed Solution
handle the mouse move away event to close the preview window or something like that.

## Alternative Solutions
Have you thought of any other ways to address this? If so, what are they?

## Potential Impact
How would this feature benefit the project and its users?

## macOS Version
macOS 15.0 Sequoia

## App Version
1.3.3

- ✅ I have reviewed the open issues to ensure this is not a duplicate feature request

**Comment by georgesnow** [comment]
i am experiencing this issue also

**Comment by 0n0mat0p03ia** [comment]
Also experiencing this issue, i.e., preview windows remaining on screen. Only way to dismiss the preview window is to mouse over it, then it disappears. Happening just often enough to be mildly frustrating. 

Issue started within the past ~3-4 weeks, approximately around when macOS 15.2 was released and DD 1.3.3 was released. Down graded to DD 1.3.2 on macOS 15.2 but issue persists.

**Comment by ejbills** [comment]
Thanks @ErickWei for reporting this issue. I've identified and fixed several edge cases where preview windows could remain on screen after mouse movement.

Changes in 1.3.4:
- Added mouse click monitoring to dismiss previews when clicking outside the window
- Implemented auto-dismissal after 10 seconds of inactivity (so windows can no longer exist after 10 seconds if they haven't been interacted with)

These changes should provide a more reliable preview dismissal experience, particularly in cases where:
- The user clicks elsewhere on screen
- The preview remains unused for an extended period

The update will be available soon. For those experiencing this on 1.3.3, upgrading to 1.3.4 when released should resolve the issues you're seeing with stuck preview windows.

**Comment by 0n0mat0p03ia** [comment]
This issue is still happening as of v1.6.1. I don't recall this being an issue until v1.3.3 and/or upgrading to macOS 15.2, perhaps both are coincidental.

@ejbills the two changes introduced in 1.4 do work, but it seems they address the symptom of the issue and not the root cause? Perhaps allowing the inactivity timeout to be a user setting would be helpful; 10 seconds is a long time for a preview window to remain on the screen IMO.
