### ISSUE TITLE
[BUG] AppleScript causes silent crash or music preview failure

### ISSUE THREAD

**Issue by Larsen2k4** [ejbills/DockDoor#967]
## Bug Description
A race condition in AppleScript handling causes DockDoor to either:

Crash silently in the background (#1038)
Stop showing music track info on subsequent hovers (#967)

## Steps to Reproduce
1. Listen to music in Music.app
2. Pause for some time and resume track or start another one
3. Widget stays inactive

## Expected vs Actual Behavior
Should always show track infos while music app is playing

## Environment
- macOS version: 26.2
- App version: 1.29 (revised version)

## Screenshots (optional)

<img width="579" height="337" alt="Image" src="https://github.com/user-attachments/assets/00e85e0c-661f-4335-a18b-6b097bf0f4c5" />

- [X] I have reviewed existing issues to ensure this is not a duplicate

**Comment by ejbills** [comment]
Is this related to #732?

**Comment by Larsen2k4** [comment]
I just checked it. No, it  also happens with music that is already downloaded/added to my library.

**Comment by Larsen2k4** [comment]
Sidenote: The same track that is playing in the screenshot showed up fine in DockDoor at first. 💡

**Comment by Larsen2k4** [comment]
Another sidenote: Everything worked fine with 1.28 and below - seems to be a change in 1.29 that's making the difference. I just rechecked it: Restarting DockDoor first shows up the song just fine and later everything is just blanked out.

**Comment by Larsen2k4** [comment]
Same problem still happening with 1.30

- Restarted DockDoor
- Startet track in Music.app (23:56)
- Played a few seconds, paused
- Hovered over Dock icon several times
- During that time: Surfing in Safari, playing some Youtube videos etc.
- No more media info shown starting 0:04

-> Another restart of DockDoor immediately brings back status of the paused track

Debug log attached. :) 

[DockDoor-Debug.log](https://github.com/user-attachments/files/24351432/DockDoor-Debug.log)

**Comment by Larsen2k4** [comment]
Update: I did a downgrade to v1.28.1 two days ago and there's been no problem with the music widget since then. Everything is working as expected again.

**Comment by ejbills** [comment]
Apple music support for apple script kind of sucks, and it wouldn't surprise me that it got worse in the latest versions of macOS. I have made no changes to the music widget backend code recently, so this must be a new development. Researching ways to avoid using applescript all together.

**Comment by Larsen2k4** [comment]
Thanks for your efforts! :) Still strange that this got quirky with 1.29+ without any change  - or is it just a newly introduced bug in macOS 26.2 ? Who knows...

Anyway: With 1.28.1 I'm doing fine, so I'll keep automatic updates disabled for now ;-)

**Comment by ejbills** [comment]
Can you try the latest beta? 1.30.1.0.15

**Comment by Larsen2k4** [comment]
Just tried the beta 1.30.1.0.17 - not working at all. Most of the time it doesn't show anything on hovering, after a few tries the app crashed. 
Also the window borders on other apps like Safari are going crazy 😅

<img width="913" height="357" alt="Image" src="https://github.com/user-attachments/assets/6034d95c-e884-4d35-8b93-09b4501ebdc3" />
<img width="421" height="294" alt="Image" src="https://github.com/user-attachments/assets/cae6ce3f-1a98-423d-b0a3-4930981111c3" />

**Comment by Larsen2k4** [comment]
...same with 1.30.1.0.18 :)

**Comment by ejbills** [comment]
> Also the window borders on other apps like Safari are going crazy

Can you record this?

**Comment by Larsen2k4** [comment]
Sure. Here you are:

https://github.com/user-attachments/assets/90a63df2-8962-4c44-8c57-b7c92785f696

**Comment by ejbills** [comment]
Beta 19 should resolve this issue

**Comment by ejbills** [comment]
Beta 22 has been released this morning which should fix the padding and music player issues. Let me know if things are still buggy, thanks!

**Comment by Larsen2k4** [comment]
Thanks for the hard work! Padding is fine now, but the music player still almost does nothing. It also is very "jumpy" and sometimes suddenly disappears while you're still on the Dock icon. I've attached another video :)

Also: If I try to open settings after some "music player trying", I get this dialog and have to quit DockDoor via Activity Monitor to use settings again (You can't open DockDoor, because it does not react):

<img width="409" height="304" alt="Image" src="https://github.com/user-attachments/assets/64b2a60c-d96c-4375-a900-3b72b1dd7409" />

https://github.com/user-attachments/assets/f55db06f-2520-4491-b3ad-dcb12278ea82

**Comment by Larsen2k4** [comment]
Oh: Another bug: After sometime DockDoor also won't generate any new windows previews (maybe that's why macOS tells me it's not reacting anymore)? It still shows my open Safari Window and Parallels Desktop, but if I click on Mail or the Finder no new previews appear.

**Comment by ejbills** [comment]
The jitteriness is a symptom of your dock hover delay being 0. Set it to 0.3 and it'll feel smoother.

**Comment by ejbills** [comment]
I have been running the apple music widget for a few hours pinned to the screen with lyrics enabled, and I have not seen a crash.

**Comment by ejbills** [comment]
All good with the latest beta? I have not seen a crash.

**Comment by Larsen2k4** [comment]
Yes, looking good so far! 👍 I also set the hover delay to 0,3 seconds - no more jittering :)

But I sometimes experience this: The widget/windows disappears while I'm just hovering over the icon. Sometimes it works, sometimes not (also happens with normal windowed apps like Safari). At the same time the launchservicesd starts to use lots of CPU power until I quit DockDoor.

https://github.com/user-attachments/assets/e8dae0ab-caeb-4adf-8c8a-b3b3773af4ff

**Comment by ejbills** [comment]
Pushing 1.30.1.0.26, thanks for the detailed report.

**Comment by clementcampagna** [comment]
Following [Release 1.30.1.0.27](https://github.com/ejbills/DockDoor/releases/tag/1.30.1.0.27) I can confirm that DockDoor does not crash anymore when hovering multiple times above Apple Music and Spotify, however, I get no more music previews on subsequent hovers.

**Comment by ejbills** [comment]
@Larsen2k4 Another patch has been released, the previous patch was not effective. I was able to get the crash on my machine, please test it out.

**Comment by ejbills** [comment]
> [1.30.1.0.27] however, I get no more music previews on subsequent hovers.

Can you wait ~30 seconds and re-hover and see if it resumes functionality?

**Comment by clementcampagna** [comment]
I tried, it doesn't. I had to close then reopen DockDoor to regain functionality.

**Comment by ejbills** [comment]
Just pushed `1.30.1.0.28` @clementcampagna - thanks again for the quick feedback. I was able to reproduce all of the issues mentioned, and this patch should cover all the issues being seen. Let me know if anything is still broken!

**Comment by clementcampagna** [comment]
Thank you for your quick updates! The latest beta works great, I'm unable to reproduce any of the issues. Fantastic job! Thanks again!

**Comment by Larsen2k4** [comment]
Agreed. Seems to be working nicely now! 😎
